name: konjo-stream

services:
  postgres:
    image: postgres
    container_name: konjo-stream-postgres
    environment:
      POSTGRES_DB: konjo-stream
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - konjo-stream_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  konjo-stream_postgres_data: